name: develop auto pr
on:
  push:
    branches: ["develop"]

jobs:
  pull-request:
    name: Open PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: tests
        run: npm test
      - uses: repo-sync/pull-request@v2
        name: pull-request-master
        with:
          destination_branch: "master"
          pr_title: "Pulling ${{ github.ref }} into master"
          pr_body: "💥 *An automated PR*"
          pr_reviewer: "jl917"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: tests
        run: npm test
      - uses: repo-sync/pull-request@v2
        name: pull-request-next
        with:
          destination_branch: "next"
          pr_title: "Pulling ${{ github.ref }} into next"
          pr_body: "💥 *An automated PR*"
          pr_reviewer: "jl917"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
